spring:
  mvc:
    favicon:
      enabled: false
  resources:
    static-locations: file:./../static
  main:
    banner_mode: 'off'
  jpa:
    hibernate:
      naming:
        physical-strategy: dvarubla.tracker.NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
server:
  port: 12345
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
---
spring:
  profiles: test
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 12347