spring:
  mvc:
    favicon:
      enabled: false
  main:
    banner_mode: 'off'
  jpa:
    hibernate:
      naming:
        physical-strategy: dvarubla.tracker.NamingStrategy
server:
  port: 12345
  ssl:
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
    keyAlias: tomcat
---
spring:
  profiles: test
server:
  port: 12347